version: '2'

services:
  bibbox-redcap:
    image: bibbox/redcap
    container_name:  bibbox-redcap
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - bibbox-redcap-db:redcap-db
    ports:
      - "8065:80"
    depends_on:
      - bibbox-redcap-db
      - bibbox-redcap-data
    volumes_from: 
      - bibbox-redcap-data

  bibbox-redcap-db:
    image: mysql:8
    container_name: bibbox-redcap-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=redcap
      - MYSQL_USER=redcap
      - MYSQL_PASSWORD=redcap4bibbox
    volumes_from: 
      - bibbox-redcap-data
    depends_on:
      - bibbox-redcap-data

  bibbox-redcap-data:
    image: busybox
    container_name: bibbox-redcap-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/www:/redcap_webroot
